universe = vanilla
log    =    log/wsb-chtc_$(Cluster)_$(Process).log
error  =  error/wsb-chtc_$(Cluster)_$(Process).err
output = output/wsb-chtc_$(Cluster)_$(Process).out

executable = ./wsb_main.sh

arguments = miniwsb.csv

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz, packages_tidyverse_sentimentr.tar.gz, SentimentCode.R, miniwsb.csv

request_cpus = 1
request_memory = 1GB
request_disk = 750MB

queue